### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by MrRooten** [gtworek/VolatileDataCollector#1]
DnsRecordListFree only free the NULL, this may cause memory leak issue

BOOL
GetDnsCachedData(
	__in IN LPWSTR Name,
	__in IN WORD Type
)
{
	/*
        Other code
         */
       while (DnsRecord != NULL) {
         /*
        Other code
         */
		DnsRecord = DnsRecord->pNext;
	}
       // Problem
	DnsRecordListFree(DnsRecord, TRUE);
       // End of Problem
// Other code
	return TRUE;
}

**Comment by gtworek** [comment]
Will take a look, thank you! I hate such leaks, but I clearly missed this one.

**Comment by gtworek** [comment]
Fixed, thanks again!
